[project]
name = "activity-coordinator-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.1.2",
    "numpy>=2.3.5",
    "ollama>=0.6.1",
    "pydantic>=2.12.5",
]

[tool.uv]
package = true
